### ISSUE TITLE
nokogumbo sometimes do it’s own escaping leading contents being escaped twice with escapeutils.

### ISSUE THREAD

**Issue by ytrezq** [rgrove/sanitize#137] opened 2015-09-27 14:10 UTC
With some elements, nokogumbo is doing it’s own ʜᴛᴍʟ escaping. If the elements aren’t whitelisted, then escapeutils does a second pass leading elements being escaped twice.
So that :

    <xmp>\<a href="https://www.google.fr">test</a></xmp>
renders :
<xmp>\<a href="https://www.google.fr">test</a></xmp>

finnally there is the \<plaintext> tag 

    <plaintext></plaintext>
<plaintext></plaintext> which while \<plaintext> being  stripped makes the whole page after it being escaped.
It even escape the final tag of the paragraph. It also can’t be closed.

**Comment by rgrove** [comment] 2015-09-28 00:03
I don't think there's a Sanitize bug here. Neither Sanitize nor Nokogumbo use escapeutils, so that piece of the puzzle is not something we have control over. 

If you're wondering why the contents of the `<xmp>` element are escaped in Sanitize's output, that's because [this is the intended behavior of the `<xmp>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/xmp).

The Gumbo parser appears to be doing the correct thing here. When it parses this input HTML...

```html
<xmp>\<a href="https://www.google.fr">test</a></xmp>
```

...Gumbo sees an `<xmp>` element, escapes its content, and then makes the parse tree available to Nokogumbo and Sanitize containing that escaped content. When Sanitize removes the non-whitelisted `<xmp>` element, it leaves its content behind. That content has already been escaped by the parser, so what you get back is:

```html
\&lt;a href="https://www.google.fr"&gt;test&lt;/a&gt;
```

If you're applying your own HTML escaping post-Sanitize, you'll need to take this into account.

The `<plaintext>` tag also appears to be working as expected. Once you open a `<plaintext>` tag, _everything_ that follows in the entire document will be [parsed as plaintext, not HTML](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/plaintext). There is no closing `</plaintext>` tag, because you _can't_ close a `<plaintext>` element. It consumes the rest of the document.

Both `<xmp>` and `<plaintext>` are obsolete tags and have been for many, many years, so I'm curious why you need to use them. I'm honestly surprised that Gumbo supports them at all! You would probably be better off using `<pre>` and/or `<code>`.

**Closed by rgrove** 2015-09-28 00:03 UTC
